#!/usr/bin/env python
import os.path
import sys
from kraki import RolfClient

def read_config():
    with open(os.path.expanduser("~/.kraki_config.txt"), "r") as kfile:
        fields = dict()
        for line in kfile.readlines():
            k, v = [p.strip() for p in line.strip().split("=")]
            fields[k] = v
        return fields['API_KEY'], fields['ROLF_BASE']

if __name__ == "__main__":
    try:
        API_KEY, ROLF_BASE = read_config()
    except IOError:
        print "Could not read API KEY from ~/.kraki_config.txt"
        sys.exit(1)

    if len(sys.argv) < 3:
        print "not enough arguments"
        print "kraki ACTION DEPLOYMENT_ID"
        sys.exit(1)
    action = sys.argv[1]
    deployment_id = sys.argv[2]
    r = RolfClient(ROLF_BASE, API_KEY)
    r.run(action, deployment_id)
